
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  job2-built-in-varaible:
    name: built-in-varaible-job
    runs-on: ubuntu-latest
    steps:
      - name: Referring context or in-built variables
        run: |
          echo "[INFO] Triggered by ${{ github.event_name }}."
          echo "[INFO] New changes are added by ${{ github.actor }} in ${{ github.head_ref }} branch."
          echo "[INFO] Current JOB ID is ${{ job.check_run_id }}."
          
  job3-staging:
    name: STAGE DEPLOYMENT
    runs-on: ubuntu-latest
    steps:
      - name: Referring Environment Variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER }}."
      - name: Reerring Envionment secrets
        run:  echo "[INFO] Password for ${{ vars.USER }} is ${{ secrets.PASSWORD }}."
    environment:
      name: STAGING
    if: github.head_ref == 'dev'

  job3-prod:
    name: PROD DEPLOYMENT
    runs-on: ubuntu-latest
    steps:
      - name: Referring Environment Variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER }}."
      - name: Referring Envionment secrets
        run:  echo "[INFO] Password for ${{ vars.USER }} is ${{ secrets.PASSWORD }}."
    environment:
      name: PRODUCTION
    if: github.ref == 'refs/heads/main'
